### ISSUE TITLE
Can not subscribe any message from topic "/ridgeback_velocity_controller/odom"

### ISSUE THREAD

**Issue by WshgL** [ridgeback/ridgeback_robot#23] opened 2018-12-18 05:16 UTC
I get some problem with odom and tf:

(1) I can not subscribe any message from topic "/ridgeback_velocity_controller/odom", But the "/status" topic is working properly. I can get the output voltage information of the motor driver from the "/status" topic. In addition, I can also control robot movement through the "/cmd_vel" topic.

(2) Because no message is available from the topic "/ridgeback_velocity_controller/odom", "/odometry/filtered" topic is also problematic. "/odometry/filtered" topic has twist information, its pose information is constantly increasing, even though my robot is still. Eventually the transformation of odom to base_link is also wrong.

![p1](https://p20.zdusercontent.com/attachment/126981/AcDR6WrvGNSJ95SVuRkhQ5QUZ?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..7-pVFeRgxwO1AKFc6w6IXg.tAoan8Des82WWklEYuhm_RChsXef20e8W3y5MdACKULaB4yCoLJZDQ7f7q2QqrP_1vYCj_gB6hbcx6gNAotYjfDPlwaVGMrNRLMmMSWWZHcs5IsWxQ-dY2XqSSNbqU1F99ltpDR0Ofh_2LcHzJYgou3NmBjb5X8T-rd6OX3YKkHKngAtJw2HxI-r8V_JOG62UCqxLiJ0eIfF6oHYoGRDtf8RFqy6qP_zQ-_Et-oAmIiER5ZqG9Xhuwkdo-BmahWJRIOlIwDlG3QjyGkU_ZwobFzwfqABRYHb9qibk5IxskQ.55m77t9Ck48lv0dn2lIYCw)

(3) When I executed "roslaunch ridgeback_viz view_robot.launch", the rviz interface told me that: the tf information is incomplete and there are multiple links that are not connected to the odom. In addition, there are some problems with time in the tf transformation. please refer to attached pictures 4_3_1, 4_3_2 and 4_3_3

```bash
No transform from [front_left_wheel_link] to [odom] 
No transform from [front_right_wheel_link] to [odom] 
No transform from [front_rocker_link] to [odom] 
No transform from [rear_left_wheel_link] to [odom] 
No transform from [rear_right_wheel_link] to [odom]

For frame [front_laser]: No transform to fixed frame [odom]. TF error: [Lookup would require extrapolation into the future. Requested time 1545108932.845590104 but the latest data is at time 36280661.233775787, when looking up transform from frame [front_laser] to frame [odom]]

Message removed because it is too old (frame=[imu_link], stamp=[34.113000000])
```

![p2](https://p20.zdusercontent.com/attachment/126981/HUoW8lgb2JGLL6Jpy9CGpk3Cc?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..PPsHllSHPivArVDOtRqwvA.Msilr4vBQhsHXwbv6bEiHySiVcGQvTmDHQmJv9xm-KRLtBH0bvMYwx9sC9uMIbEzaThpkdFAPv7YKfZYmpy9ehzt3oCBzwhZS8QF7pmT4mih3dI8crH0dN8chzQxql1S-XjRFzf3Z7RpbpY_LjgMoGjaLPGlKKcLbHE9wQWL9L924QKYa9ZY6XSCy2uivE2FbUEqhe2rqr8uav79oCv1ReKX3AlPMwJefUwDld6O_U0MRXzHrKZJz9-AMWkReY_Ma9fnc7F0XjDplS9DfXyksfnYAyuzCcDDf7F2S8VBXXs.7yGImNus6DOUz9tVeygKfQ)
![p3](https://p20.zdusercontent.com/attachment/126981/GEEEnVFmiem8uw8GFtRXeuvV0?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..7bBie5kYz0PIwMyRdn5jQw.qi_yjiF6-hYoVThw7Xr6YBe4sc4MAsMjiwMu9fSWkoZ1cpe82NRlGkN02gqPrV62ygIWpoLUwpsZx-fJa-io8jzWzbWkDWX9ioeYV95DYae-50Pd3_dJydzUiertju4aCIawyevG6qK1FzO0ffHcHGVTmA7cFiwhvjpkIShq5vjnovACBAn7aw8CR2oo52x8gV5aUyVeFZ2SeK7u8Fn7VncgdLdUnNQkcaKMyRFJhhRPeL_FYaGz40laRvHcKwlzAIXS6ImGpskO8XkkYzjrHuB57TOumC0hTsermAPIGL4.byloo9GkhY47ytMtk6hfUg)
![p4](https://p20.zdusercontent.com/attachment/126981/u231xgoyLfULpYx2LXeJmcZBn?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..8LdLxc4-322YJpf09cxHGw.oXx1J3konwMtCY4pXw9DkVQ264ElCSi5C6DFRCY5YUGnQ4-zA0k899BKVv2H3n7BxHTD4Fode1XrVcwP_cvTT4RQ7FJk_9-N8r2iOdijwrtvzzyoJ4V0SUaCxjhR56RLtNEEfx5r4AuN3a7Rqsi7qfsnqQv_DlDT2FcBwmDQV7aXNXbyOuUBYLLUsI0JIyYi_D5qyWauE9SqjA_HzeoTMkFxGbX9ISY5iv_uaDjKtkPdLZ0Mm1fMY9alfEMuPqS9FuuJOFJpluf--IyMark89vSZwMVFSHbmn2dnC_tMtNs.YVQYcEVrtgFAXrXJZ8DZ-w)

**Comment by tonybaltovski** [comment] 2018-12-19 00:19
Closing due to duplicate of ridgeback/ridgeback#27.

**Closed as completed by tonybaltovski** 2018-12-19 00:19 UTC
